language: php

php:
  - 7.1
  - 7.2
  - nightly

sudo: false

addons:
  apt:
    packages:
      - libxml2-utils

cache:
  directories:
    - $HOME/.composer/cache

env:
  global:
    - PATH="$HOME/.composer/vendor/bin:$PATH"
    - SYMFONY_DEPRECATIONS_HELPER=weak
    - TARGET=test

matrix:
  fast_finish: true
  include:
    - php: 7.2
      env: TARGET=lint
    - php: 7.2
      env: TARGET=phpstan
    - php: 7.1
      env: COMPOSER_FLAGS="--prefer-lowest"
    - php: 7.2
      env: SYMFONY_VERSION=3.4.*
    - php: 7.2
      env: SYMFONY_VERSION=4.0.*
  allow_failures:
    - php: nightly

install:
 - wget "http://cs.sensiolabs.org/download/php-cs-fixer-v2.phar" --output-document="${HOME}/bin/php-cs-fixer" && chmod u+x "${HOME}/bin/php-cs-fixer"
 - wget "https://github.com/php-coveralls/php-coveralls/releases/download/v2.0.0/php-coveralls.phar" --output-document="${HOME}/bin/php-coveralls" && chmod u+x "${HOME}/bin/php-coveralls"
 - wget "https://phar.phpunit.de/phpunit-6.5.phar" --output-document="${HOME}/bin/phpunit" && chmod u+x "${HOME}/bin/phpunit"
 - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;
 - if [ "$TARGET" == "lint" ]; then gem install yaml-lint && composer global require --dev sllh/composer-lint --no-update; fi
 - if [ "$TARGET" == "phpstan" ]; then composer global require --dev phpstan/phpstan phpstan/phpstan-phpunit --no-update; fi
 - if [ "$TARGET" != "test" ]; then composer global update; fi
 - composer update --prefer-dist --no-interaction $COMPOSER_FLAGS

script: make $TARGET

after_success:
 - php-coveralls -v
