language: php

php:
  - 7.2
  - nightly

sudo: false

addons:
  apt:
    packages:
      - libxml2-utils

cache:
  directories:
    - $HOME/.composer/cache

env:
  global:
    - PATH="$HOME/.composer/vendor/bin:$PATH"
    - SYMFONY_DEPRECATIONS_HELPER=weak_vendors
    - TARGET=test

stages:
    - lint
    - dependencies
    - test

matrix:
  fast_finish: true
  include:
    - stage: lint
      php: 7.2
      env: TARGET=lint
    - stage: lint
      php: 7.2
      env: TARGET=phpstan
    - stage: dependencies
      php: 7.2
      env: TARGET=checkdeps
    - stage: test
      php: 7.2
      env: COMPOSER_FLAGS="--prefer-lowest"
    - stage: test
      php: 7.2
      env: SYMFONY_VERSION=3.4.*
    - stage: test
      php: 7.2
      env: SYMFONY_VERSION=4.0.*
  allow_failures:
    - php: nightly
    - php: 7.2
      env: TARGET=checkdeps

before_install:
 - wget "https://github.com/php-coveralls/php-coveralls/releases/download/v2.0.0/php-coveralls.phar" --output-document="${HOME}/bin/php-coveralls" && chmod u+x "${HOME}/bin/php-coveralls"
 - gem install yaml-lint

install:
 - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;
 - composer update --prefer-dist --no-interaction $COMPOSER_FLAGS

script: make $TARGET

after_success:
 - php-coveralls -v
