language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

sudo: false

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.cache/pip

env:
  global:
    - PATH="$HOME/.composer/vendor/bin:$PATH"
    - SYMFONY_DEPRECATIONS_HELPER=weak

matrix:
  fast_finish: true
  include:
    - php: 5.6
      env: CS_FIXER=run
    - php: 5.6
      env: SECURITY_CHECKER=run
    - php: 5.5
      env: COMPOSER_FLAGS="--prefer-lowest"
    - php: 5.6
      env: SYMFONY_VERSION=2.3.*
    - php: 5.6
      env: SYMFONY_VERSION=2.6.*
    - php: 5.6
      env: SYMFONY_VERSION=2.7.*
    - php: 5.6
      env: SYMFONY_VERSION=2.8.*
    - php: 5.5
      env: SYMFONY_VERSION="3.0.*" ACL_VERSION="dev-master"
    - php: 5.6
      env: SYMFONY_VERSION="3.0.*" ACL_VERSION="dev-master"
    - php: 7.0
      env: SYMFONY_VERSION="3.0.*" ACL_VERSION="dev-master"
  allow_failures:
    - php: hhvm

before_script:
  - mkdir -p ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d && echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - composer selfupdate
  - composer config -q -g github-oauth.github.com $GITHUB_OAUTH_TOKEN
  - composer global require phpunit/phpunit:@stable fabpot/php-cs-fixer sensiolabs/security-checker --no-update
  - composer global update --prefer-dist --no-interaction
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;
  - if [ "$ACL_VERSION" != "" ]; then composer require "symfony/security-acl:${ACL_VERSION}" --no-update; fi;
  - travis_wait composer update --prefer-dist --no-interaction $COMPOSER_FLAGS
  - export PATH=$HOME/.local/bin:$PATH

script:
 - if [ "$CS_FIXER" = "run" ]; then make cs_dry_run ; fi;
 - if [ "$SECURITY_CHECKER" = "run" ]; then make check ; fi;
 - make test
