language: php

php:
  - 5.6
  - 7.0
  - nightly
  - hhvm

sudo: false

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.cache/pip

env:
  global:
    - PATH="$HOME/.composer/vendor/bin:$PATH"
    - SYMFONY_DEPRECATIONS_HELPER=weak
    - TARGET=test

matrix:
  fast_finish: true
  include:
    - php: 7.0
      env: TARGET=cs_dry_run
    - php: 5.6
      env: COMPOSER_FLAGS="--prefer-lowest"
    - php: 7.0
      env: SYMFONY_VERSION=2.7.*
    - php: 7.0
      env: SYMFONY_VERSION=2.8.*
    - php: 7.0
      env: SYMFONY_VERSION=3.0.*
    - php: 7.0
      env: SYMFONY_VERSION=3.1.*
  allow_failures:
    - php: hhvm
    - php: nightly

before_script:
  - (phpenv config-rm xdebug.ini || exit 0)
  - mkdir -p ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d && echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - composer selfupdate
  - composer config -q -g github-oauth.github.com $GITHUB_OAUTH_TOKEN
  - composer global update --prefer-dist --no-interaction
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;
  - travis_wait composer update --prefer-dist --no-interaction $COMPOSER_FLAGS
  - export PATH=$HOME/.local/bin:$PATH

script:
 - make $TARGET
