# https://dependabot.com/docs/config-file/

version: 1

update_configs:
  - commit_message:
      prefix: "[DEP]"
    default_labels:
      - "dependency"
    directory: "/"
    automerged_updates:
      - match:
          dependency_type: "development"
    default_assignees:
      - "core23"     
    default_labels:
      - "dependency"
    default_reviewers:
      - "core23"     
    package_manager: "php:composer"
    update_schedule: "live"
    version_requirement_updates: "widen_ranges"
